#!/usr/bin/env python
from setup_utils import *
import os

# authn_anon
def undeploy():
    app = actions.getAppName("authn_anon.ear")
    if app: actions.undeploy(app)
    app = actions.getAppName("authn_anon")
    if app: actions.undeploy(app)
    app = actions.getAppName("authn.anon")
    if app: actions.undeploy(app)
    
actions, arg, props = getActions("authn_anon-setup.properties", [])

prop_name = "authn_anon.properties"
prop_list = []

if arg in ["CONFIGURE", "INSTALL"]:
    actions.configure(prop_name, prop_list)
    actions.checkNoErrors()
    
if arg == "INSTALL":
               
    getProperties(prop_name, prop_list)       
           
    actions.installFile(prop_name)
    
    try:
        undeploy()
        actions.deploy(deploymentorder=80)
        app = actions.getAppName("icat.server")
        if app: actions.restartApp(app)           
    except Exception, e:
        abort(str(e))
               
if arg == "UNINSTALL":
    actions.removeFile(prop_name)
    
    try:
        undeploy()
    except Exception, e:
        abort(str(e))       
    
            
    
